### ISSUE TITLE
Input is of type object, but not of type string.

### ISSUE THREAD

**Issue by EhsanSarshar** [SebastianG77/find-duplicated-property-keys#1]
when importing json to find duplicate.

```
const findDuplicatedPropertyKeys = require('find-duplicated-property-keys');

const jsonString = require('./categories.json');

const result = findDuplicatedPropertyKeys(jsonString);

console.log(result.toString());
```

**Comment by SebastianG77** [comment]
Hi @EhsanSarshar ,

unfortunately you cannot use the module like that, because `require('./categories.json');` already parses the file content of ./categories.json to a JavaScript Object that does not contain duplicates anymore. In your example the function `findDuplicatedPropertyKeys(jsonString);` would not receive any information about existing duplicates. Hence, it is essential to read the file content as a String and pass this value to the function `findDuplicatedPropertyKeys(jsonString);`. 

Try the following to make the module work as desired:

```
const fs = require('fs')

const findDuplicatedPropertyKeys = require('find-duplicated-property-keys');

const jsonString = fs.readFileSync('./categories.json', {encoding: 'utf-8'});

result = findDuplicatedPropertyKeys(jsonString)

console.log(result.toString())
```

**Comment by SebastianG77** [comment]
I am closing this issue as I did not get any feedback for a week. I assume your problem has been solved.

Feel free to contact me again if you still have any questions.
