### ISSUE TITLE
What about .isArray?

### ISSUE THREAD

**Issue by rklec** [SebastianG77/find-duplicated-property-keys#3]
I'm struggling to understand in what case the `.isArray`. How can a property(?`) in a JSON string be a duplicate and be an array?

## Try

I tried it with this JSON, but it passes, respectively has no problem:
```json
{
"DuplicatedPropertyInObjectOfArray": [
    1337,
    1337
  ],
}
```

**Edit:** Okay, that's obviously a valid JSON with two array elements, so what's up here?

## The doc

The current Readme/[doc](https://www.npmjs.com/package/find-duplicated-property-keys?activeTab=readme) also does not document that property. It is, however, always available.

## TypeScript

As I use TypeScript, I've installed [`@types/find-duplicated-property-keys`](https://www.npmjs.com/package/@types/find-duplicated-property-keys) and [it actually exposes that key](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/23ef99ad1e052282c61b240187026fa687c9f688/types/find-duplicated-property-keys/index.d.ts#L28-L31), so I assume it is part of the public API of this npm package?

If it is not (and only used internally), then maybe the `@types` package has to be adjusted.

**Comment by SebastianG77** [comment]
Hi @rklec,

it is a while ago since I have written the code, but property isArray is only meant to be used internally for function toString(), which is the reason, why I did not describe it in the docs. The change was introduced in 99efff2dcf06b7047578fc8d7c93ecd697311d66. A test case was added in c2c110d84db663fc71e3e682c930b1f477a948c6.

With this change the toString() was changed, such that if you run this function for the JSON object
```json
{
  "myObject": [{
    "name": "Me",
    "name": "You"
  }]
}
```

the string representation '\<instance\>.myObject[0].name' will be returned. However, before that the toString() method returned '\<instance\>.myObject.[0].name', because array and object representation were the same.

I am not familiar with the type script version. Is there a possibility to adjust my code, such that typescript will not handle this property as a public one?

Kind regards,
Sebastian

**Comment by rklec** [comment]
> I am not familiar with the type script version. Is there a possibility to adjust my code, such that typescript will not handle this property as a public one?

No, AFAIK, `@types` needs to be adjusted, but I can do that.

**Comment by rklec** [comment]
So thanks a lot for your reply. I am also not an expert for that kind of stuff, but I've submitted https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57479 as a PR. I guess this question is solved here, so I am closing this.

**Comment by peterblazejewicz** [comment]
change merged in the upstream, should be published to NPM (updated @types/*) soon
