### ISSUE TITLE
Updating node targert in babelrc to 14.x

### ISSUE THREAD

**Issue by hyperupcall** [SebastianG77/find-duplicated-property-keys#4]
Hi,

I noticed the `.babelrc` targets Node v8.x, but the oldest LTS is v14.x. Can the babelrc be updated?

**Comment by SebastianG77** [comment]
Hi @hyperupcall,

thanks a lot for your input & happy new year to you! Apparently nodeJs 8 is not supported anymore. So basically it would be a good idea to update. On the other hand updating minimum supported nodeJS version would cause an incompatible change, which I would like to avoid, as systems using node 8 might not be able to run the code anymore.

Anyway, I agree with avoiding outdated technology. So we probably should update the target node version.

When checking EOLs (https://nodejs.dev/en/about/releases/), it only makes sense to update to node 18. I am going to update the nodeJS target version and check if it causes any issues. If everything works fine, I will push the update. Otherwise, I will let you know why I prefer the current state.

Kind regards,
Sebastian

**Comment by hyperupcall** [comment]
hello and happy new years to you too!

sounds good - 18 would probably work for me too, as long as the output is CommonJS and not ESModules. I would love to use Modules, but unfortunately, as a user of Grunt, that's not possible atm

**Comment by SebastianG77** [comment]
Hi @hyperupcall ,

did you actually had any issues with the latest version? I have updated target version on this branch https://github.com/SebastianG77/find-duplicated-property-keys/tree/increase_transpiled_nodejs_version but the output looks identical to the old implementation.

**Comment by hyperupcall** [comment]
Hmm, I just tried it myself, and yeah it does look the same - upon further inspection, you don't seem to be removing any features that require Babel.

I don't remember what I saw that made me create the issue, so I'm going to closet his issue. Thank you for your investigation!
